### ISSUE TITLE
Whether there are plans to support vmd animation

### ISSUE THREAD

**Issue by Spencer17x** [noname0310/babylon-mmd#1]
Such as the title

**Comment by noname0310** [comment]
Yes, I'm planning to support vmd animation.

Right now it's very early and only pmx and vmd parsing are fully implemented at the moment.

See here for a complete mmd loader that works with your browser
https://github.com/noname0310/web-mmd-viewer

**Comment by Spencer17x** [comment]
Thank you for your answer! This example requires threejs, I'm currently running into a requirement for babylonjs, but I'm not good at it, any good suggestions

**Comment by noname0310** [comment]
Right now, there is no way to load pmx/vmd data directly from Babylon.js And that's what this repository is trying to do

As far as I know, forking the web-mmd-viewer is the most reliable way to play mmd on the web for now. It's based on three.js, of course

**Comment by Spencer17x** [comment]
Yes, I know that Babylon.js can’t directly load pmx/vmd. What I want to know is that there is a plan to implement Babylon.js in the library babylon-mmd to directly load vmd and display animations. I read that there are three natural MMDLoader Support, but it is difficult for me to port to Babylon.js or write related Babylon.js plug-ins. I am not good at this convenience, so I would like to ask for help 😭

**Comment by noname0310** [comment]
You just have to wait. loader plugin will be implemented soon
