### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'errorTextureDatas')     at _MmdAsyncTextureLoader._addErrorTextureReferenceCount

### ISSUE THREAD

**Issue by spencer17x** [noname0310/babylon-mmd#10]
<img width="1440" alt="image" src="https://github.com/noname0310/babylon-mmd/assets/32794413/324c08e9-9679-472b-90a1-6f1d2a877553">

**Comment by spencer17x** [comment]
[米雪儿炼狱_by_卡拉彼丘_13e60d28cf440b5c753247fdea0f393b.zip](https://github.com/noname0310/babylon-mmd/files/12287993/_by_._13e60d28cf440b5c753247fdea0f393b.zip)

**Comment by noname0310** [comment]
Related to issue #9. I will release the 0.23.0 version now, so please test it again

**Comment by spencer17x** [comment]
> Related to issue #9. I will release the 0.23.0 version now, so please test it again

0.23.0 resolved.
