### ISSUE TITLE
Texture load/shader compilation delay

### ISSUE THREAD

**Issue by spencer17x** [noname0310/babylon-mmd#11]
https://github.com/noname0310/babylon-mmd/assets/32794413/4d6939c0-af0c-4edd-8228-20df530a0945

 When loading the model, he renders it white without textures.

**Comment by spencer17x** [comment]
Maybe you can use something like Promise.all to solve this problem？

**Comment by spencer17x** [comment]
Can't importMeshAsync solve this problem？

**Comment by noname0310** [comment]
> It's in the answer I gave you

**Comment by noname0310** [comment]
Now things will go as you want. However, as it doesn't seem to be a particularly important factor, I won't update the version right now. If you have an urgent matter, please let me know.

**Comment by spencer17x** [comment]
If you think this can be fixed with pr, then I can try to bring up a pr.

**Comment by noname0310** [comment]
There seems to be a misunderstanding It's already solved and I just haven't updated the npm package version yet

**Comment by spencer17x** [comment]
Are you referring to the problem of this issue? If yes, please inform me if there is any package to update npm, thank you

**Comment by noname0310** [comment]
I mean I don't seem to need to do npm publish right now because the severity of this problem seems low

**Comment by spencer17x** [comment]
Yes, but I hope you'll let me know if this issue is fixed after the next npm package is released, which I think is an optimization

**Comment by noname0310** [comment]
Okay, I'll let you know when 0.24.0 released

I plan to do a new release when [this issue](https://forum.babylonjs.com/t/havok-physics-rigidbody-dont-move-when-the-damping-values-of-several-bodies-are-different/43072/5) is resolved.

**Comment by spencer17x** [comment]
Nice bro! And i suggest that you use Link Commits to GitHub Issues, which will make it clearer which issues are resolved by which commits, and it will also help your project to be more robust and maintainable.

**Comment by noname0310** [comment]
I think commit already linked this issue

https://github.com/noname0310/babylon-mmd/commit/88a059600e7776ca2a66b1c13f2bbca526cddc64

**Comment by spencer17x** [comment]
Nice，i saw it.

**Comment by noname0310** [comment]
0.24.0 is released now

**Comment by spencer17x** [comment]
Nice job! It is solved.
