### ISSUE TITLE
The model in the form of file cannot be loaded normally

### ISSUE THREAD

**Issue by spencer17x** [noname0310/babylon-mmd#12]
When your model was uploaded as a file, the load failed：
<img width="1433" alt="image" src="https://github.com/noname0310/babylon-mmd/assets/32794413/754e36b6-6b63-4cf3-8aa5-fe5e53d81026">

**Comment by noname0310** [comment]
- make sure that you are static serving the texture file.

- Is there a case difference between the file path you are requesting and the actual file path?
    - If so, you must use pmx editor to match the file path case. Or even if you convert it to bpmx, it will be fixed.
