### ISSUE TITLE
Whether other character models can load vmd animation format

### ISSUE THREAD

**Issue by spencer17x** [noname0310/babylon-mmd#13]

**Comment by noname0310** [comment]
The easiest way is to simply use a solution that converts your model to PMX format.

**Comment by noname0310** [comment]
As of version 0.29.0, it is now possible to drive humanoid models into the MMD runtime.

To be precise, `HumanoidMmd` provides the ability to create an `MmdModel` from a humanoid mesh

You can check out the test code here:
https://github.com/noname0310/babylon-mmd/blob/main/src/Test/Scene/humanoidMmdTestScene.ts
https://github.com/noname0310/babylon-mmd/blob/main/src/Test/Scene/humanoidMmdTestScene2.ts

Documentation will be written later, so if you have any questions, please open an issue
