### ISSUE TITLE
Is there a way to bind or attach a pmx model to the bones of a character model?

### ISSUE THREAD

**Issue by TopSea** [noname0310/babylon-mmd#17]
Like holding a sword.

![sword](https://github.com/noname0310/babylon-mmd/assets/44743008/874f54cd-5d64-4bc2-a529-d994bb937f48)

**Comment by noname0310** [comment]
I think this is the simplest way

https://playground.babylonjs.com/#028YR6#7
```typescript
const box = MeshBuilder.CreateBox("Box");
const rightWrist = modelMesh.metadata.skeleton.bones.find(bone => bone.name === "右手首");
box.parent = rightWrist;
```
