### ISSUE TITLE
The project won't work

### ISSUE THREAD

**Issue by Spencer17x** [noname0310/babylon-mmd#2]
I cloned this project, but after executing the readme, the project reported an error and did not work properly.
The same goes for npm packages

**Comment by noname0310** [comment]
Please tell me the details of the error with the code

**Comment by Spencer17x** [comment]
When I run, I get the following error
<img width="548" alt="image" src="https://github.com/noname0310/babylon-mmd/assets/32794413/cf7f3728-9c76-4210-9a27-c38da2ed0895">

**Comment by noname0310** [comment]
pmx and vmd files are required. Due to licensing issues, the assets are not included in the source.

**Comment by Spencer17x** [comment]
Failure to load：https://a-cdn.qbox.net/test/models/vmd/wavefile_v2.vmd
<img width="574" alt="image" src="https://github.com/noname0310/babylon-mmd/assets/32794413/329d3454-8112-4422-8218-4fa1f9495d09">

**Comment by noname0310** [comment]
You must load vmd with VmdLoader.

Aren't you using BvmdLoader?

**Comment by Spencer17x** [comment]
I used the vmdloader to load the vmd, but did not use the bvmdloader

**Comment by Spencer17x** [comment]
So is bvmd necessary?

**Comment by noname0310** [comment]
bvmd is optional. And I think it's a CORS problem. Please host the static files locally and give them a try.

**Comment by Spencer17x** [comment]
No, I had the same problem with it locally, you can download it and test it

**Comment by noname0310** [comment]
There is not enough information to know the cause

**Comment by Spencer17x** [comment]
You can use https://a-cdn.qbox.net/test/models/vmd/wavefile_v2.vmd for testing

**Comment by noname0310** [comment]
I fixed it now, so you can use the 0.5.0 version.

**Comment by Spencer17x** [comment]
How to make pmx file execute vmd animation, I tested seems not to work

**Comment by noname0310** [comment]
If you could show me the code, I might be able to identify the problem.

**Comment by Spencer17x** [comment]
const model = await SceneLoader.ImportMeshAsync(
				'',
				'/models/pmx/[MODELS] Lovesick girls ver.1/[LSG] Jennie (Miku) ver.1.pmx',
				'',
			).then((result) => result.meshes[0]);
			console.log('model', model);
			const vmdLoader = new VmdLoader(scene);
			const modelMotion = await vmdLoader.loadAsync("", "https://a-cdn.qbox.net/test/models/vmd/wavefile_v2.vmd");
			const mmdRuntime = new MmdRuntime();
			const mmdModel = mmdRuntime.createMmdModel(model);
			mmdModel.addAnimation(modelMotion);
			mmdModel.setAnimation("model_motion_1");
			mmdRuntime.register(scene);

**Comment by noname0310** [comment]
```typescript
const pmxLoader = new PmxLoader();
SceneLoader.RegisterPlugin(pmxLoader);
const model = await SceneLoader.ImportMeshAsync(
  '',
  '/models/pmx/[MODELS] Lovesick girls ver.1/[LSG] Jennie (Miku) ver.1.pmx',
  '',
).then((result) => result.meshes[0]);
console.log('model', model);
const vmdLoader = new VmdLoader(scene);
const modelMotion = await vmdLoader.loadAsync("model_motion_1", "https://a-cdn.qbox.net/test/models/vmd/wavefile_v2.vmd");
const mmdRuntime = new MmdRuntime();
const mmdModel = mmdRuntime.createMmdModel(model);
mmdModel.addAnimation(modelMotion);
mmdModel.setAnimation("model_motion_1");
mmdRuntime.register(scene);
mmdRuntime.playAnimation();
```

It should be work
