### ISSUE TITLE
Observable for speed and volume change

### ISSUE THREAD

**Issue by SavAct** [noname0310/babylon-mmd#23]
When changing the speed in the audio player menu, the observable never fires:
```TS
const audioPlayer = new StreamAudioPlayer(scene);
audioPlayer.onPlaybackRateChangedObservable.add(() => {
    console.log('Will never be called');
});
```
Since this affects the animation speed, the observable should probably be a property of MmdRuntime instead. 
It seems MmdRuntime is also missing a property to change the animation speed.

By the way, is there also an observable for volume changes?

**Comment by noname0310** [comment]
#Close the issue for the reasons mentioned in 24.
