### ISSUE TITLE
Rendering of hidden meshes

### ISSUE THREAD

**Issue by SavAct** [noname0310/babylon-mmd#26]
Many models contain meshes with `isVisible` set to `false`. Depending on the `renderMethod`, these meshes either remain invisible or appear completely black when set to `isVisible = true`. This black appearance only occurs when using `MmdStandardMaterialRenderMethod.AlphaEvaluation`.

In this mode, the mesh reveals its true color when covered by a slightly transparent UI element, as shown in the comparison images:
![image](https://github.com/user-attachments/assets/7c4684c9-3681-4ce4-a350-61c5ec1b748c)
![image](https://github.com/user-attachments/assets/2b75b355-8a38-4c2f-a717-0d22e472934c)

On Android AR mode, these black meshes turn completely white. On VR headsets (Meta Quest 3), the meshes display their real colors but appear slightly transparent.

This issue might be related to the following console output during `loadAssetContainerAsync` execution that repeat several times:
![image](https://github.com/user-attachments/assets/0adc8fb3-8acb-4685-8610-ea216559066d)
The log pushes out my whole index.html and complain about it `Offending line [10] in vertex code: <!doctype html>`
![image](https://github.com/user-attachments/assets/927bd99a-937f-4ec1-860e-1c6770638914)

Is this a known issue, or am I doing something wrong?

**Comment by noname0310** [comment]
The error seems to be caused by vite not properly handling async imports with side effects.

Try adding the following two import statements directly to your project 
```
import "babylon-mmd/esm/Loader/Shaders/textureAlphaChecker.fragment";
import "babylon-mmd/esm/Loader/Shaders/textureAlphaChecker.vertex";
```

And apart from that error, the `MmdStandardMaterialRenderMethod.AlphaEvaluation` mode does not provide acceptable results for some models.

Models loaded using this method will be configured to follow the rendering method commonly used by babylon.js, rather than the rendering method used by MMD. This can introduce artifacts in the process. It's impossible for an automated algorithm to perfectly resolve them.

Therefore, `AlphaEvaluation` is not suitable unless you are in a scenario where you load your model and then manually change the material settings to fix it.

See the jsdoc for the `MmdStandardMaterialRenderMethod` enum
https://github.com/noname0310/babylon-mmd/blob/main/src/Loader/mmdStandardMaterialBuilder.ts#L22-L59

**Comment by SavAct** [comment]
The error log disappears after including additional imports. However, the visibility issue with the meshes persist. I conducted the following tests:

- Using [babylon-mmd-viewer](https://github.com/noname0310/babylon-mmd-viewer) with all meshes set to visible: The meshes display correctly, but only when using `MmdStandardMaterialRenderMethod.AlphaEvaluation`. Otherwise, they remain invisible.

- Using [babylon-mmd-vite-template](https://github.com/noname0310/babylon-mmd-vite-template) with `AlphaEvaluation`: The meshes are visible but appear completely white instead of black.

- Replacing webpack with vite in [babylon-mmd-viewer](https://github.com/noname0310/babylon-mmd-viewer): The result is the same as with webpack. The meshes are visible with correct textures, but only with `AlphaEvaluation`.

If you have no other suggestions, my next step would be to exchange the code line by line between the vite version of [babylon-mmd-viewer](https://github.com/noname0310/babylon-mmd-viewer) and [babylon-mmd-vite-template](https://github.com/noname0310/babylon-mmd-vite-template) until the effect appears

**Comment by noname0310** [comment]
I forgot and didn't explain properly about meshes with isVisible false, forcing this to be true can be problematic.
Meshes that are not visible when loaded will not actually be invisible when loaded into mmd. These meshes usually have a toggle controlled by the material morph, so you can use the `MmdMoprhController` to toggle them off and on.

**Comment by SavAct** [comment]
Yes, your Vite implemention helped a lot and improved the transpiling time multiple times. I also switched some times back to webpack but until now it never fixed my issues. Therefore, I think you did a pretty good job with the vite setup.

> I forgot and didn't explain properly about meshes with isVisible false, forcing this to be true can be problematic. Meshes that are not visible when loaded will not actually be invisible when loaded into mmd. These meshes usually have a toggle controlled by the material morph, so you can use the `MmdMoprhController` to toggle them off and on.
> 
> To recap, manipulating the isVisible property of a mesh directly can cause different behavior than MMD. In order to toggle the mesh properly, you should use the toggle morph that the PMX model author has put in place.

That was exactly my problem, thank you for pointing that out. By using morth instead, most meshes will now be displayed (sorry, if that was obviouse for MMD creators. I was not into MMD before this project).

Just some meshes that are set to `isVisible == false` by default remain invisible, regardless of the morph weights and `MmdStandardMaterialRenderMethod`. Perhaps I'm missing something else that is also MMD specific.

**Comment by noname0310** [comment]
> Just some meshes that are set to `isVisible == false` by default remain invisible, regardless of the morph weights and `MmdStandardMaterialRenderMethod`. Perhaps I'm missing something else that is also MMD specific.

If it's visible in MMD *(MMD is the name of the software)* , you don't need to make it visible. If it's not, it's probably the library issue.

**Comment by SavAct** [comment]
In the English version of PMXView these meshes has the `Opaque` value of `0`. By changing it to 1 and storing the pmx file it is visible in babylon-mmd.
![image](https://github.com/user-attachments/assets/902e1dfc-4acb-4c15-8316-fabc530876fe)
Is there any way to change this value with babylon-mmd? (Ideally at runtime, after loading the model)

**Comment by noname0310** [comment]
Try this:
```
material.alpha = 1.0;
```

**Comment by SavAct** [comment]
It works with 
```TS
material.alpha = 1.0;
material.isVisible = true;
```
Thanks, finally all meshes can be displayed
