### ISSUE TITLE
How do I drive the model

### ISSUE THREAD

**Issue by Spencer17x** [noname0310/babylon-mmd#4]
If I have some data about my face and body, how do I drive the model

**Comment by noname0310** [comment]
I don't know what data you're talking about. You need to be more specific.

Everything loaded by the loader conforms to the specifications of Babylon.js.
Therefore, most of the things you want can be solved based on the documentation of Babylon.js.

**Comment by Spencer17x** [comment]
Whether a general method can be provided for manipulating bone or deformation，like：https://github.com/virtual-cast/babylon-vrm-loader/tree/master

**Comment by noname0310** [comment]
That is the interface that is possible because the vrm bone structure is guaranteed to be constant.

PMX cannot create such an interface because of its free bone structure, and even if it can, such an interface adversely affects performance and bundle size.

**Comment by noname0310** [comment]
https://github.com/noname0310/babylon-mmd/blob/main/src/runtime/animation/MmdRuntimeAnimation.ts#L345C1-L345C1

A sample bone binding code can be found in this link.

**Comment by Spencer17x** [comment]
What does 'the vrm bone structure is guaranteed to be constant.' and 'PMX cannot create such an interface because of its free bone structure' mean?

**Comment by noname0310** [comment]
https://docs.unity3d.com/ScriptReference/HumanBodyBones.html
VRM Loader allows static mapping based on name because it ensures a bone hierarchy that follows the structure of HumanBodyBones.

https://github.com/virtual-cast/babylon-vrm-loader/blob/master/src/humanoid-bone.ts
And that functionality is naturally implemented through hardcoding, merely mapping bone names. Therefore, the absence of that feature does not cause any issues in manipulating PMX models.

**Comment by Spencer17x** [comment]
The mmd plugin for threejs supports this feature, would you consider supporting it

**Comment by noname0310** [comment]
I've never heard of it. I don't even know what exactly you're talking about.
can you give me a related reference?

**Comment by Spencer17x** [comment]
Just like the vrm loader, it drives the face and bones

**Comment by noname0310** [comment]
As I said above, all operations are already possible with the feature of Babylon.js.

This operation is possible through the `Bone` class in Babylon.js, and for `MorphTargetManager` class in the case of MorphTarget.

And you can also manipulate morphs that operate at mmd runtime through `MmdModel.morph`.

**Comment by Spencer17x** [comment]
Okay, thank you

**Comment by noname0310** [comment]
There is no further discussion, so I will close the issue. If you have any other questions, please feel free to post new issues
