### ISSUE TITLE
Whether there are plans to support the pmd format

### ISSUE THREAD

**Issue by spencer17x** [noname0310/babylon-mmd#7]
Such as title

**Comment by noname0310** [comment]
(I want you to know the context that babylon-mmd was made for modern MMD, not for nostalgia)
The pmd format is not currently used well, so there are no implementation plans yet.

You can open the pmd file in [PMX Editor](https://www.deviantart.com/johnwithlenon/art/PmxEditor-v0273-English-Version-unofficial-trans-925125044) and save it as pmx.

If you want to support the pmd file, please let me know the reason.

**Comment by spencer17x** [comment]
Because the MMDLoader of three.js supports PMD, PMX, VMD, and VPD files

**Comment by noname0310** [comment]
I think it's hard to give a reason that we have to implement it as well because three.js MMDLoader is implementing it. Rather than that, I'm asking the essential reason for loading pmd or vpd.

**Comment by noname0310** [comment]
To make babylon-mmd the most solid solution for loading mmd in browsers, I implemented a pmd loader this week.

Check the [changelog](https://github.com/noname0310/babylon-mmd/releases/tag/v0.28.0) for details.
