### ISSUE TITLE
Model texture .tga format supports

### ISSUE THREAD

**Issue by spencer17x** [noname0310/babylon-mmd#9]
playground：https://playground.babylonjs.com/#ZF86YL#17

expect：
<img width="1074" alt="image" src="https://github.com/noname0310/babylon-mmd/assets/32794413/58801d0b-ec56-4554-b322-2eff2564f85d">

**Comment by noname0310** [comment]
![image](https://github.com/noname0310/babylon-mmd/assets/48761044/e88319b1-a0e6-4cba-b12d-3606cbe4fda5)
There doesn't seem to be a problem

If you created an issue because of alpha blending, it is a problem that cannot be completely solved.

The method I recommend the most is to do fix material on the BPMX converter.
https://noname0310.github.io/babylon-mmd/docs/deep-usage/convert-pmx-model-into-bpmx/

**Comment by spencer17x** [comment]
Have you tested whether either of these options works？Do you think it's a problem with the model itself?If you think this is a problem with the model itself, why does this work well on mmd's software?

**Comment by spencer17x** [comment]
It also displays normally in blender:
<img width="482" alt="image" src="https://github.com/noname0310/babylon-mmd/assets/32794413/de70f182-dd72-428e-9380-85c4d21eeba5">

**Comment by spencer17x** [comment]
At babylon-mmd@0.6.0, it is also displayed normally：
<img width="777" alt="image" src="https://github.com/noname0310/babylon-mmd/assets/32794413/d383deab-4c91-4b55-850b-ef3289b829bd">

**Comment by noname0310** [comment]
Upon analyzing the cause, it seems that the model is using the TGA image format. I will look into ways to provide support for it.

And creating an instance of the PmxLoader is no longer a normal way of using the loader.
```typescript
const pmxLoader = new PmxLoader();
```

Instead, side effects should be used.
```typescript
import "babylon-mmd/esm/Loader/pmxLoader";

const pmxLoader = SceneLoader.GetPluginForExtension(".pmx") as PmxLoader;
```

**Comment by spencer17x** [comment]
I tested it and it didn't work

**Comment by noname0310** [comment]
That is not directly related to the problem.

I'm working on this right now.

**Comment by spencer17x** [comment]
> [ad9f451](https://github.com/noname0310/babylon-mmd/commit/ad9f4516c0a0ac9a7e80359ccbecbeac32c0830b)
> 
> This commit will resolves the issue.

0.23.0 resolved.
